#include "kn/diag.h"

// Implemented in kn_diag.c
void kn_diag_register_seed_code(const char *code, int severity, const char *title, const char *detail);

typedef struct
{
    const char *code;
    int severity;
    const char *title;
    const char *detail;
} KnDiagSeedEntry;

static const KnDiagSeedEntry g_diag_registry[] = {
    { "E-GEN-00001", 0, "Abstract Method", "Class must implement abstract base method" },
    { "E-SEM-00001", 0, "Access Violation", "Private member not accessible" },
    { "E-SEM-00002", 0, "Access Violation", "Protected member not accessible" },
    { "E-RES-00001", 0, "Ambiguous Function", "Multiple functions match; use qualified name" },
    { "E-ARG-00001", 0, "Argument Count", "Wrong number of arguments" },
    { "E-ARG-00002", 0, "Invalid Named Argument", "Positional argument cannot follow named argument" },
    { "E-ARG-00003", 0, "Invalid Named Argument", "Named arguments are not supported for this callable" },
    { "E-ARG-00004", 0, "Invalid Named Argument", "Named arguments are not supported for constructors" },
    { "E-ARG-00005", 0, "Duplicate Named Argument", "Duplicate named argument" },
    { "E-GEN-00002", 0, "Array Length", "Initializer has too many elements" },
    { "E-GEN-00003", 0, "Byte Overflow", "byte range is 0..255" },
    { "E-GEN-00004", 0, "Const Assignment", "Cannot assign to const variable" },
    { "E-GEN-00005", 0, "Const Assignment", "Cannot modify const variable" },
    { "E-GEN-00006", 0, "Const Requires Init", "Const variable must have initializer" },
    { "E-GEN-00007", 0, "Constructor", "Constructor not found" },
    { "E-GEN-00008", 0, "Conversion Syntax Changed", "Type conversion now use [type](value) syntax instead of type(value). For example: [int](\"123\") instead of int(\"123\")" },
    { "E-GEN-00009", 0, "Conversion Syntax Changed", "Type conversion now use [type](value) syntax instead of type(value). " },
    { "E-NAM-00001", 0, "Duplicate Class", "Class already defined" },
    { "E-NAM-00002", 0, "Duplicate Constructor", "Constructor already defined" },
    { "E-NAM-00003", 0, "Duplicate Enum", "Enum already defined" },
    { "E-NAM-00004", 0, "Duplicate Enum", "Enum member already defined" },
    { "E-NAM-00005", 0, "Duplicate Field", "Field already defined" },
    { "E-NAM-00006", 0, "Duplicate Function", "Function already defined" },
    { "E-NAM-00007", 0, "Duplicate Interface", "Interface already defined" },
    { "E-NAM-00008", 0, "Duplicate Interface", "Interface already listed" },
    { "E-NAM-00009", 0, "Duplicate Method", "Interface method already defined" },
    { "E-NAM-00010", 0, "Duplicate Method", "Method already defined" },
    { "E-NAM-00011", 0, "Duplicate Struct", "Struct already defined" },
    { "E-NAM-00012", 0, "Duplicate Symbol", "Variable already defined in this scope" },
    { "E-ENT-00001", 0, "Entry Ambiguous", "Multiple Main functions found" },
    { "E-ENT-00002", 0, "Entry Signature", "Main must be Static" },
    { "E-ENT-00003", 0, "Entry Signature", "Main must return int" },
    { "E-ENT-00004", 0, "Entry Signature", "Main must take zero or one parameter" },
    { "E-ENT-00005", 0, "Entry Signature", "Main parameter must be string[]" },
    { "E-SYN-00001", 0, "Expected '/>'", "Missing '/>' after block body" },
    { "E-GEN-00010", 0, "Generic Arity", "Wrong number of generic type arguments" },
    { "E-GEN-00011", 0, "Generic Function", "Failed to resolve instantiated generic function" },
    { "E-GEN-00012", 0, "Generic Function", "Generic call requires explicit type arguments" },
    { "E-GEN-00013", 0, "Generic Function", "Generic function reference requires explicit type arguments" },
    { "E-GEN-00014", 0, "Interface Method", "Class must implement interface method" },
    { "E-GEN-00015", 0, "Interface Method", "Interface implementation must be public" },
    { "E-SEM-00003", 0, "Invalid Abstract", "Abstract method requires abstract class" },
    { "E-SEM-00004", 0, "Invalid Address", "Address-of array not supported" },
    { "E-SEM-00005", 0, "Invalid Address", "Address-of requires an assignable expression" },
    { "E-SEM-00006", 0, "Invalid Align", "Align must be power of two" },
    { "E-SEM-00007", 0, "Invalid Assignment", "Cannot assign to enum constant" },
    { "E-SEM-00008", 0, "Invalid Assignment", "Cannot modify enum constant" },
    { "E-SEM-00009", 0, "Invalid Assignment", "Increment/decrement target must be assignable" },
    { "E-SEM-00010", 0, "Invalid Assignment", "Left-hand side must be assignable" },
    { "E-SEM-00011", 0, "Invalid Assignment", "Target is not assignable" },
    { "E-SEM-00012", 0, "Invalid Attribute", "Attributes are not supported on global variables" },
    { "E-SEM-00013", 0, "Invalid Base", "Base is not available in static context" },
    { "E-SEM-00014", 0, "Invalid Base", "Class has no base type" },
    { "E-SEM-00015", 0, "Invalid Call", "Block object must use Run/Jump APIs" },
    { "E-SEM-00016", 0, "Invalid Call", "Call target is not a function object" },
    { "E-SEM-00017", 0, "Invalid Call", "Static method requires class name" },
    { "E-TYP-00001", 0, "Invalid Cast", "Cannot cast Object values; use Object conversions instead" },
    { "E-TYP-00002", 0, "Invalid Cast", "Cannot cast to Object types; use Object conversions instead" },
    { "E-SEM-00018", 0, "Invalid Catch", "Catch parameter must be string or IO.Error" },
    { "E-SEM-00019", 0, "Invalid Constructor", "Constructor cannot be static/virtual/override/abstract/sealed" },
    { "E-CTL-00001", 0, "Invalid Control Flow", "break/continue not in loop" },
    { "E-SEM-00020", 0, "Invalid Enum", "Enum underlying type must be integer" },
    { "E-SEM-00021", 0, "Invalid Generic Call", "Builtin function does not accept generic type arguments" },
    { "E-SEM-00022", 0, "Invalid Generic Call", "Function object invocation does not accept generic type arguments" },
    { "E-SEM-00023", 0, "Invalid Generic Call", "Type arguments are only valid for generic function calls" },
    { "E-SEM-00024", 0, "Invalid Generic Call", "Type arguments can only be used with generic functions" },
    { "E-SEM-00025", 0, "Invalid Get Position", "Get must appear at top-level after Unit and before declarations" },
    { "E-SEM-00026", 0, "Invalid Global", "Only variable declarations are allowed at global scope" },
    { "E-SEM-00027", 0, "Invalid Index", "Indexing requires array, string or pointer" },
    { "E-SEM-00028", 0, "Invalid Inheritance", "Cannot inherit from sealed class" },
    { "E-SEM-00029", 0, "Invalid Inheritance", "Class cannot inherit from itself" },
    { "E-SEM-00030", 0, "Invalid Interface", "Interface methods must be abstract" },
    { "E-SEM-00031", 0, "Invalid Member", "Interface members not supported yet" },
    { "E-SEM-00032", 0, "Invalid Member", "Member access requires class instance" },
    { "E-SEM-00033", 0, "Invalid Member", "Member call requires class instance" },
    { "E-SEM-00034", 0, "Invalid Modifier", "Sealed is only valid on override methods" },
    { "E-SEM-00035", 0, "Invalid Modifier", "Static methods cannot be virtual/override/abstract" },
    { "E-SEM-00036", 0, "Invalid New", "Cannot instantiate abstract class" },
    { "E-SEM-00037", 0, "Invalid Operator", "Unknown binary operator" },
    { "E-SEM-00038", 0, "Invalid Operator", "Unknown unary operator" },
    { "E-SEM-00039", 0, "Invalid Override", "Base method is sealed" },
    { "E-SEM-00040", 0, "Invalid Override", "No virtual base method to override" },
    { "E-CTL-00002", 0, "Invalid Return", "Return is not allowed inside Block" },
    { "E-SEM-00041", 0, "Invalid This", "This is not available in static context" },
    { "E-CTL-00003", 0, "Invalid Throw", "Throw expression must be string or IO.Error" },
    { "E-CTL-00004", 0, "Invalid Throw", "Throw requires an expression" },
    { "E-TYP-00003", 0, "Invalid Type", "Array element name missing" },
    { "E-TYP-00004", 0, "Invalid Type", "Array element type unknown" },
    { "E-TYP-00005", 0, "Invalid Type", "Type not specified" },
    { "E-TYP-00006", 0, "Invalid Type", "Void not allowed here" },
    { "E-TYP-00007", 0, "Invalid Type", "any[] requires explicit length" },
    { "E-SEM-00042", 0, "Missing Entry", "Main function not found" },
    { "E-SEM-00043", 0, "Missing Get", "Standard module not imported; add a Get statement" },
    { "E-SEM-00044", 0, "Missing Override", "Method hides a virtual base method" },
    { "E-CTL-00005", 0, "Missing Return", "Non-void function must return a value on all paths" },
    { "E-CTL-00006", 0, "Missing Return", "Non-void method must return a value on all paths" },
    { "E-NAM-00013", 0, "Name Conflict", "Class conflicts with enum name" },
    { "E-NAM-00014", 0, "Name Conflict", "Class conflicts with interface name" },
    { "E-NAM-00015", 0, "Name Conflict", "Class conflicts with struct name" },
    { "E-NAM-00016", 0, "Name Conflict", "Interface conflicts with enum name" },
    { "E-NAM-00017", 0, "Name Conflict", "Interface conflicts with struct name" },
    { "E-NAM-00018", 0, "Name Conflict", "Struct conflicts with enum name" },
    { "E-CTL-00007", 0, "Return Outside Function", "Return not allowed here" },
    { "E-CTL-00008", 0, "Return Type", "Non-void function must return a value" },
    { "E-CTL-00009", 0, "Return Type", "Void function cannot return a value" },
    { "E-GEN-00016", 0, "Scoped Symbol Required", "Imported symbol must be called with module or alias qualifier" },
    { "E-CTL-00010", 0, "Throw Outside Function", "Throw not allowed here" },
    { "E-TYP-00008", 0, "Type Inference Failed", "Array element type requires initializer" },
    { "E-TYP-00009", 0, "Type Inference Failed", "Cannot infer element type from empty array" },
    { "E-TYP-00010", 0, "Type Inference Failed", "Var requires initializer" },
    { "E-TYP-00011", 0, "Type Mismatch", "Type mismatch" },
    { "E-SYN-00002", 0, "Unexpected Token", "Unexpected token in expression" },
    { "E-RES-00002", 0, "Unknown Base", "Base class not found" },
    { "E-RES-00003", 0, "Unknown Base", "Base class or interface not found" },
    { "E-RES-00004", 0, "Unknown Enum Member", "Enum member not found" },
    { "E-RES-00005", 0, "Unknown Expression", "Unsupported expression" },
    { "E-RES-00006", 0, "Unknown Extern Binding", "Supported bindings are C and System" },
    { "E-RES-00007", 0, "Unknown Field", "Field not found" },
    { "E-RES-00008", 0, "Unknown Function", "Builtin function reference not found" },
    { "E-RES-00009", 0, "Unknown Function", "Function not found" },
    { "E-RES-00010", 0, "Unknown Interface", "Interface not found" },
    { "E-RES-00011", 0, "Unknown Method", "Interface method not found" },
    { "E-RES-00012", 0, "Unknown Method", "Method not found" },
    { "E-RES-00013", 0, "Unknown Method", "Static method not found" },
    { "E-RES-00014", 0, "Unknown Specifier", "Unsupported struct specifier" },
    { "E-RES-00015", 0, "Unknown Symbol", "Symbol not found in module" },
    { "E-RES-00016", 0, "Unknown Type", "Cast target type is unknown" },
    { "E-RES-00017", 0, "Unknown Type", "Class not found" },
    { "E-RES-00018", 0, "Unknown Type", "Class or interface not found" },
    { "E-RES-00019", 0, "Unknown Type", "Enum not found" },
    { "E-RES-00020", 0, "Unknown Type", "Struct not found" },
    { "E-RES-00021", 0, "Unknown Variable", "Assignment target not found" },
    { "E-RES-00022", 0, "Unknown Variable", "Variable not defined" },
    { "E-RES-00023", 0, "Unknown Parameter", "Unknown named argument" },
    { "E-GEN-00017", 0, "Unsupported Generic Method", "Generic methods are not supported" },
    { "E-SEM-00045", 0, "Unsafe Block", "Record inside nested control flow requires Unsafe Block" },
    { "E-SEM-00046", 0, "Unsafe Call", "Safe function cannot call Unsafe" },
    { "E-TYP-00012", 0, "Unsupported Type", "Type not supported yet" },
    { "W-SAF-00001", 1, "Entry Unsafe", "Entry point is marked as Unsafe. This disables safety guarantees for the entire program. Consider using Safe Main and isolating Unsafe blocks locally." },
    { "W-SYN-00001", 1, "Legacy Array Syntax", "Use 'Type[] name' instead of 'Type name[]'" },
    { "W-SYN-00002", 1, "Legacy Constructor Syntax", "Use 'Constructor(...)' instead of 'Function ClassName(...)'" },
    { "W-LNT-00001", 1, "Unused Variable", "Variable is never used" },
    { "W-LNT-00002", 1, "Unreachable Code", "Unreachable code" },
    { "E-SYN-00003", 0, "Expected '('", "Missing '('" },
    { "E-SYN-00004", 0, "Expected '('", "Missing '(' after Align" },
    { "E-SYN-00005", 0, "Expected '('", "Missing '(' after Constructor" },
    { "E-SYN-00006", 0, "Expected '('", "Missing '(' after If" },
    { "E-SYN-00007", 0, "Expected '('", "Missing '(' after cast type" },
    { "E-SYN-00008", 0, "Expected '('", "Missing '(' after class name" },
    { "E-SYN-00009", 0, "Expected '('", "Missing '(' after function name" },
    { "E-SYN-00010", 0, "Expected '('", "Missing '(' after function return type" },
    { "E-SYN-00011", 0, "Expected '('", "Missing '(' after method name" },
    { "E-SYN-00012", 0, "Expected ')'", "Missing ')'" },
    { "E-SYN-00013", 0, "Expected ')'", "Missing ')' after Align" },
    { "E-SYN-00014", 0, "Expected ')'", "Missing ')' after If condition" },
    { "E-SYN-00015", 0, "Expected ')'", "Missing ')' after catch parameter" },
    { "E-SYN-00016", 0, "Expected ')'", "Missing ')' after for clause" },
    { "E-SYN-00017", 0, "Expected ')'", "Missing ')' after parameters" },
    { "E-SYN-00018", 0, "Expected ')'", "Missing ')' in attribute" },
    { "E-SYN-00019", 0, "Expected ')'", "Missing ')' in call" },
    { "E-SYN-00020", 0, "Expected ')'", "Missing ')' in cast expression" },
    { "E-SYN-00021", 0, "Expected ')'", "Missing ')' in constructor call" },
    { "E-SYN-00022", 0, "Expected ')'", "Missing ')' in member call" },
    { "E-SYN-00023", 0, "Expected '/'", "Missing '/>' after block body" },
    { "E-SYN-00024", 0, "Expected '/'", "Missing '</' before block body" },
    { "E-SYN-00025", 0, "Expected ':'", "Missing ':' in conditional expression" },
    { "E-SYN-00026", 0, "Expected '<'", "Missing '</' before block body" },
    { "E-SYN-00027", 0, "Expected '<'", "Missing '<' before generic type arguments" },
    { "E-SYN-00028", 0, "Expected '>'", "Missing '/>' after block body" },
    { "E-SYN-00029", 0, "Expected '>'", "Missing '>' after generic type arguments" },
    { "E-SYN-00030", 0, "Expected '>'", "Missing '>' after generic type parameter list" },
    { "E-SYN-00031", 0, "Expected '['", "Missing '[' in cast expression" },
    { "E-SYN-00032", 0, "Expected ']'", "Missing ']'" },
    { "E-SYN-00033", 0, "Expected ']'", "Missing ']' after attribute" },
    { "E-SYN-00034", 0, "Expected ']'", "Missing ']' after index" },
    { "E-SYN-00035", 0, "Expected ']'", "Missing ']' in cast expression" },
    { "E-SYN-00036", 0, "Expected '{'", "Missing '{'" },
    { "E-SYN-00037", 0, "Expected '{'", "Missing '{' in Else expression" },
    { "E-SYN-00038", 0, "Expected '{'", "Missing '{' in If expression" },
    { "E-SYN-00039", 0, "Expected '{'", "Missing '{' in class" },
    { "E-SYN-00040", 0, "Expected '{'", "Missing '{' in enum" },
    { "E-SYN-00041", 0, "Expected '{'", "Missing '{' in interface" },
    { "E-SYN-00042", 0, "Expected '{'", "Missing '{' in struct" },
    { "E-SYN-00043", 0, "Expected '}'", "Missing '}'" },
    { "E-SYN-00044", 0, "Expected '}'", "Missing '}' in Else expression" },
    { "E-SYN-00045", 0, "Expected '}'", "Missing '}' in If expression" },
    { "E-SYN-00046", 0, "Expected '}'", "Missing '}' in array literal" },
    { "E-SYN-00047", 0, "Expected '}'", "Missing '}' in enum" },
    { "E-SYN-00048", 0, "Unexpected End Of File", "Unexpected end of file while parsing expression" },
    { "E-SYN-00049", 0, "Unexpected End Of File", "Unexpected end of file while parsing variable declaration" },
    { "E-SYN-00050", 0, "Unterminated String Literal", "String literal is missing a closing quote" },
    { "E-SYN-00051", 0, "Expected Block", "Expected 'Block' keyword" },
    { "E-SYN-00052", 0, "Expected Catch", "Missing 'Catch' after Try block" },
    { "E-SYN-00053", 0, "Expected Class", "Expected 'Class' keyword" },
    { "E-SYN-00054", 0, "Expected Constructor", "Expected 'Constructor' keyword" },
    { "E-SYN-00055", 0, "Expected Else", "If expression requires Else branch" },
    { "E-SYN-00056", 0, "Expected Enum", "Expected 'Enum' keyword" },
    { "E-SYN-00057", 0, "Expected For", "Expected 'For' keyword" },
    { "E-SYN-00058", 0, "Expected Function", "Expected 'Function' keyword" },
    { "E-SYN-00059", 0, "Expected Get", "Expected 'Get' keyword" },
    { "E-SYN-00060", 0, "Expected Identifier", "Expected block name" },
    { "E-SYN-00061", 0, "Expected Identifier", "Expected block variable name" },
    { "E-SYN-00062", 0, "Expected Identifier", "Expected catch variable name" },
    { "E-SYN-00063", 0, "Expected Identifier", "Expected class name" },
    { "E-SYN-00064", 0, "Expected Identifier", "Expected enum member" },
    { "E-SYN-00065", 0, "Expected Identifier", "Expected enum name" },
    { "E-SYN-00066", 0, "Expected Identifier", "Expected field name" },
    { "E-SYN-00067", 0, "Expected Identifier", "Expected function name" },
    { "E-SYN-00068", 0, "Expected Identifier", "Expected generic type parameter name" },
    { "E-SYN-00069", 0, "Expected Identifier", "Expected interface name" },
    { "E-SYN-00070", 0, "Expected Identifier", "Expected method name" },
    { "E-SYN-00071", 0, "Expected Identifier", "Expected name" },
    { "E-SYN-00072", 0, "Expected Identifier", "Expected parameter name" },
    { "E-SYN-00073", 0, "Expected Identifier", "Expected record name" },
    { "E-SYN-00074", 0, "Expected Identifier", "Expected remote name" },
    { "E-SYN-00075", 0, "Expected Identifier", "Expected specifier" },
    { "E-SYN-00076", 0, "Expected Identifier", "Expected struct name" },
    { "E-SYN-00077", 0, "Expected Identifier", "Expected variable name" },
    { "E-SYN-00078", 0, "Expected Identifier", "Extern binding requires an identifier (C/System)" },
    { "E-SYN-00079", 0, "Expected If", "Expected 'If' keyword" },
    { "E-SYN-00080", 0, "Expected If", "Expected 'If' keyword in expression" },
    { "E-SYN-00081", 0, "Expected Interface", "Expected 'Interface' keyword" },
    { "E-SYN-00082", 0, "Expected Jump", "Expected 'Jump' keyword" },
    { "E-SYN-00083", 0, "Expected Number", "Align requires a number" },
    { "E-SYN-00084", 0, "Expected Number", "Enum value requires a number" },
    { "E-SYN-00085", 0, "Expected Record", "Expected 'Record' keyword" },
    { "E-SYN-00086", 0, "Expected Semicolon", "Abstract method requires ';'" },
    { "E-SYN-00087", 0, "Expected Semicolon", "Extern function requires ';'" },
    { "E-SYN-00088", 0, "Expected Semicolon", "Missing ';' after Get" },
    { "E-SYN-00089", 0, "Expected Semicolon", "Missing ';' after Jump" },
    { "E-SYN-00090", 0, "Expected Semicolon", "Missing ';' after Throw" },
    { "E-SYN-00091", 0, "Expected Semicolon", "Missing ';' after Unit" },
    { "E-SYN-00092", 0, "Expected Semicolon", "Missing ';' after break" },
    { "E-SYN-00093", 0, "Expected Semicolon", "Missing ';' after continue" },
    { "E-SYN-00094", 0, "Expected Semicolon", "Missing ';' after declaration" },
    { "E-SYN-00095", 0, "Expected Semicolon", "Missing ';' after expression" },
    { "E-SYN-00096", 0, "Expected Semicolon", "Missing ';' after field" },
    { "E-SYN-00097", 0, "Expected Semicolon", "Missing ';' after for condition" },
    { "E-SYN-00098", 0, "Expected Semicolon", "Missing ';' after return" },
    { "E-SYN-00099", 0, "Expected Semicolon", "Missing ';' after variable declaration" },
    { "E-SYN-00100", 0, "Expected Semicolon", "Missing ';' in for initializer" },
    { "E-SYN-00101", 0, "Expected Struct", "Expected 'Struct' keyword" },
    { "E-SYN-00102", 0, "Expected Throw", "Expected 'Throw' keyword" },
    { "E-SYN-00103", 0, "Expected Try", "Expected 'Try' keyword" },
    { "E-SYN-00104", 0, "Expected While", "Expected 'While' keyword" },
    { "E-SYN-00105", 0, "Expected '}'", "Unexpected end of file while parsing block" },
    { "E-SEM-00047", 0, "Invalid Generic Call", "Generic type arguments are only supported on named function calls" },
    { "E-SEM-00048", 0, "Invalid Generic Function", "Extern function cannot be generic" },
    { "E-SEM-00049", 0, "Invalid Generic Member", "Generic type arguments on member access require a call" },
    { "E-SEM-00050", 0, "Invalid Generic Type", "Expected a type argument" },
    { "E-GEN-00018", 0, "Unsupported Generic Local Function", "Generic local named functions are not supported yet" },
    { "E-GEN-00019", 0, "Unsupported Generic Method", "Generic methods are not supported yet" },
    { "E-SYN-00106", 0, "Unexpected Top-Level Token", "Expected a top-level declaration (Function/Class/Struct/Enum/Interface/variable declaration)" },
};

void kn_diag_register_builtin_templates(void)
{
    for (int i = 0; i < (int)(sizeof(g_diag_registry) / sizeof(g_diag_registry[0])); i++)
        kn_diag_register_seed_code(g_diag_registry[i].code, g_diag_registry[i].severity, g_diag_registry[i].title, g_diag_registry[i].detail);
}
