from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TESTS_ROOT = ROOT / "tests"
DEFAULT_OUTPUT_DIR = ROOT / "artifacts" / "superdocs"
DOCS_OUTPUT_NAME = "english-superdocs.md"
TESTS_OUTPUT_NAME = "tests-superdocs.md"
MANIFEST_NAMES = ("manifest.json", "smoke.json", "freestanding.json")
KNOWN_PLATFORMS = ("windows", "linux", "macos")
EXCLUDED_DOC_DIRS = {
    ".git",
    ".venv",
    "__pycache__",
    "artifacts",
    "node_modules",
    "out",
    "third_party",
}


@dataclass(frozen=True)
class TestCaseRef:
    manifest_name: str
    case_name: str
    direction: str
    execution: str
    platforms: tuple[str, ...]


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def normalize_rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n")


def should_skip_doc_file(path: Path) -> bool:
    rel = normalize_rel(path)
    if path.suffix.lower() != ".md":
        return True
    if path.name.endswith(".zh-CN.md"):
        return True
    if "zh-CN" in path.parts:
        return True
    return False


def collect_english_docs() -> list[Path]:
    files: list[Path] = []
    for current_root, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [name for name in dirnames if name not in EXCLUDED_DOC_DIRS]
        current_path = Path(current_root)
        for filename in filenames:
            path = current_path / filename
            if should_skip_doc_file(path):
                continue
            files.append(path)
    files.sort(key=doc_sort_key)
    return files


def doc_sort_key(path: Path) -> tuple[int, str]:
    rel = path.relative_to(ROOT)
    rel_str = rel.as_posix().lower()
    if rel == Path("README.md"):
        return (0, rel_str)
    if rel.parent == Path("."):
        return (1, rel_str)
    if rel.parts[0] == "docs":
        return (2, rel_str)
    if rel.parts[0] == "dev":
        return (3, rel_str)
    return (4, rel_str)


def render_english_superdocs(files: list[Path]) -> str:
    lines = [
        "<!-- Generated by infra.scripts.superdocs -->",
        f"Generated at: {utc_now_iso()}",
        f"Included English Markdown files: {len(files)}",
        "",
    ]
    for path in files:
        lines.extend(
            [
                "---",
                "",
                f"# {path.name}",
                "",
                f"Path: `{normalize_rel(path)}`",
                "",
                read_text(path).rstrip(),
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def iter_case_kn_paths(case: dict[str, object]) -> list[str]:
    values: list[str] = []
    single = case.get("file")
    if isinstance(single, str):
        values.append(single)
    many = case.get("files")
    if isinstance(many, list):
        for item in many:
            if isinstance(item, str):
                values.append(item)
    return [Path(value).as_posix() for value in values if value.endswith(".kn")]


def infer_platforms_from_path(rel_path: str) -> tuple[str, ...]:
    parts = Path(rel_path).parts
    return tuple(platform for platform in KNOWN_PLATFORMS if platform in parts)


def case_platforms(case: dict[str, object]) -> tuple[str, ...]:
    raw = case.get("platforms")
    if isinstance(raw, list):
        values = tuple(str(item).strip() for item in raw if str(item).strip())
        if values:
            return tuple(dict.fromkeys(values))
    paths = iter_case_kn_paths(case)
    if paths:
        inferred = infer_platforms_from_path(paths[0])
        if inferred:
            return inferred
    return ()


def case_execution(case: dict[str, object]) -> str:
    if case.get("expect_error"):
        return "expected compiler error"
    if bool(case.get("compile_only", False)):
        return "compile only"
    return "runtime"


def case_direction(case: dict[str, object]) -> str:
    return "negative" if case.get("expect_error") else "positive"


def collect_test_case_refs() -> dict[str, list[TestCaseRef]]:
    refs: dict[str, list[TestCaseRef]] = {}
    for manifest_name in MANIFEST_NAMES:
        manifest_path = TESTS_ROOT / manifest_name
        payload = json.loads(read_text(manifest_path))
        if not isinstance(payload, list):
            raise SystemExit(f"unexpected manifest payload: {manifest_path}")
        for case in payload:
            if not isinstance(case, dict):
                continue
            name = str(case.get("name") or "")
            ref = TestCaseRef(
                manifest_name=manifest_name,
                case_name=name,
                direction=case_direction(case),
                execution=case_execution(case),
                platforms=case_platforms(case),
            )
            for rel_path in iter_case_kn_paths(case):
                refs.setdefault(rel_path, []).append(ref)
    for rel_path in refs:
        refs[rel_path].sort(key=lambda item: (item.manifest_name, item.case_name, item.execution))
    return refs


def collect_test_files() -> list[Path]:
    files = sorted(TESTS_ROOT.rglob("*.kn"), key=lambda item: normalize_rel(item).lower())
    return [path for path in files if "__pycache__" not in path.parts]


def inferred_direction(rel_path: str) -> tuple[str, str]:
    parts_lower = [part.lower() for part in Path(rel_path).parts]
    name_lower = Path(rel_path).name.lower()
    if name_lower.startswith("error_") or any("bad" in part for part in parts_lower):
        return ("Negative (inferred)", "Not listed in JSON manifests; inferred from filename or path.")
    return ("Positive (inferred support file)", "Not listed in JSON manifests; treated as a support/source file.")


def summarize_direction(rel_path: str, refs: list[TestCaseRef]) -> tuple[str, str]:
    if not refs:
        return inferred_direction(rel_path)
    directions = {ref.direction for ref in refs}
    if directions == {"positive"}:
        return ("Positive", "All referenced manifest cases are positive.")
    if directions == {"negative"}:
        return ("Negative", "All referenced manifest cases are negative.")
    return ("Mixed (positive + negative)", "Referenced by both positive and negative manifest cases.")


def summarize_scope(rel_path: str, refs: list[TestCaseRef]) -> str:
    if not refs:
        inferred = infer_platforms_from_path(rel_path)
        if inferred:
            return f"Platform-limited ({', '.join(inferred)})"
        return "Common"

    unique_platform_sets = {ref.platforms for ref in refs}
    if unique_platform_sets == {()}:
        return "Common"

    merged = sorted({platform for platforms in unique_platform_sets for platform in platforms})
    if () in unique_platform_sets:
        return f"Mixed (common + {', '.join(merged)})"
    return f"Platform-limited ({', '.join(merged)})"


def summarize_execution(refs: list[TestCaseRef]) -> str:
    if not refs:
        return "Unlisted/support file"
    labels = sorted({ref.execution for ref in refs})
    if len(labels) == 1:
        return labels[0].capitalize()
    return "Mixed (" + " + ".join(label.capitalize() for label in labels) + ")"


def summarize_coverage(refs: list[TestCaseRef]) -> str:
    if not refs:
        return "None"
    labels = [f"{ref.manifest_name}:{ref.case_name} [{ref.execution}]" for ref in refs]
    return ", ".join(labels)


def render_tests_superdocs(files: list[Path], refs_by_path: dict[str, list[TestCaseRef]]) -> str:
    lines = [
        "<!-- Generated by infra.scripts.superdocs -->",
        f"Generated at: {utc_now_iso()}",
        f"Included test source files: {len(files)}",
        "",
    ]
    for path in files:
        rel_path = normalize_rel(path)
        refs = refs_by_path.get(rel_path, [])
        direction, direction_note = summarize_direction(rel_path, refs)
        lines.extend(
            [
                "---",
                "",
                f"# {path.name}",
                "",
                f"Path: `{rel_path}`",
                f"Direction: {direction}",
                f"Scope: {summarize_scope(rel_path, refs)}",
                f"Execution: {summarize_execution(refs)}",
                f"Coverage: {summarize_coverage(refs)}",
                f"Notes: {direction_note}",
                "",
                "```kn",
                read_text(path).rstrip(),
                "```",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate Kinal documentation and test superdocs")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="directory that will receive the generated superdocs",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    output_dir = args.output_dir.resolve()

    docs = collect_english_docs()
    refs_by_path = collect_test_case_refs()
    tests = collect_test_files()

    docs_output = output_dir / DOCS_OUTPUT_NAME
    tests_output = output_dir / TESTS_OUTPUT_NAME

    write_text(docs_output, render_english_superdocs(docs))
    write_text(tests_output, render_tests_superdocs(tests, refs_by_path))

    print(f"[OK] wrote English superdocs: {docs_output}")
    print(f"[OK] English Markdown files included: {len(docs)}")
    print(f"[OK] wrote test superdocs: {tests_output}")
    print(f"[OK] test source files included: {len(tests)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
