"""Regenerate the pure-Kinal diagnostic catalog from the stage0 locale sources."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DESTINATION = ROOT / "apps/kinal-selfhost/src/IO/Kinal/Compiler/Core/DiagnosticCatalog.kn"


def generate() -> str:
    source = (ROOT / "apps/kinal/src/kn_diag_registry.c").read_text(encoding="utf-8")
    chinese = json.loads((ROOT / "infra/assets/locales/zh-CN.json").read_text(encoding="utf-8"))
    pattern = r'\{\s*("(?:[^"\\]|\\.)*"),\s*[01],\s*("(?:[^"\\]|\\.)*"),\s*("(?:[^"\\]|\\.)*")\s*\}'
    quote = lambda value: json.dumps(value, ensure_ascii=False)
    lines = ["Unit IO.Kinal.Compiler.Core.DiagnosticCatalog;", "",
             "Get IO.Kinal.Compiler.Core.Localization;", "",
             "// Generated by infra/scripts/sync_selfhost_diagnostic_catalog.py.",
             "// English codes and translations mirror the stage0 diagnostic registry and",
             "// infra/assets/locales/zh-CN.json; verify updates with the generator's --check.",
             "// Runtime lookup, fallback and external JSON loading are pure Kinal.",
             "Safe Function list CreateCatalog()", "{", "    list entries = list.Create();"]
    for raw in re.findall(pattern, source):
        code, title, detail = map(json.loads, raw)
        translated = chinese.get(code, {})
        values = (code, title, detail, translated.get("title", ""), translated.get("detail", ""))
        lines.append("    entries.Add(New DiagnosticTemplate(" + ", ".join(map(quote, values)) + "));")
    lines += ["    Return entries;", "}", "", "Safe Function string ChineseUi(string key)", "{"]
    ui = {"ui.stage.lexer": "词法分析", "ui.stage.project": "项目", "ui.stage.driver": "驱动",
          "ui.stage.link": "链接", "ui.stage.native": "本机代码", "ui.stage.knc": "字节码",
          "ui.diag.location": "在 <{0}> 第 {1} 行，第 {2} 列"}
    for key, value in chinese.items():
        if "text" in value and key.startswith(("ui.stage.", "ui.severity.")):
            ui[key] = value["text"]
    for key, value in ui.items():
        lines.append(f"    If (key == {quote(key)}) Return {quote(value)};")
    lines += ['    Return "";', "}", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if DESTINATION.read_text(encoding="utf-8") != expected:
            raise SystemExit("selfhost diagnostic catalog is stale; run infra/scripts/sync_selfhost_diagnostic_catalog.py")
    else:
        DESTINATION.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
