"""Regenerate the pure-Kinal diagnostic catalog from the stage0 locale sources."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DESTINATION = ROOT / "apps/kinal-selfhost/src/IO/Kinal/Compiler/Core/DiagnosticCatalog.kn"


def generate() -> str:
    source = (ROOT / "apps/kinal/src/kn_diag_registry.c").read_text(encoding="utf-8")
    chinese = json.loads((ROOT / "infra/assets/locales/zh-CN.json").read_text(encoding="utf-8"))
    pattern = r'\{\s*("(?:[^"\\]|\\.)*"),\s*[01],\s*("(?:[^"\\]|\\.)*"),\s*("(?:[^"\\]|\\.)*")\s*\}'
    quote = lambda value: json.dumps(value, ensure_ascii=False)
    lines = ["Unit IO.Kinal.Compiler.Core.DiagnosticCatalog;", "",
             "Get IO.Kinal.Compiler.Core.Localization;", "",
             "// Generated by infra/scripts/sync_selfhost_diagnostic_catalog.py.",
             "// English codes and translations mirror the stage0 diagnostic registry and",
             "// infra/assets/locales/zh-CN.json; verify updates with the generator's --check.",
             "// Runtime lookup, fallback and external JSON loading are pure Kinal.",
             "Safe Function list CreateCatalog()", "{", "    list entries = list.Create();"]
    for raw in re.findall(pattern, source):
        code, title, detail = map(json.loads, raw)
        translated = chinese.get(code, {})
        values = (code, title, detail, translated.get("title", ""), translated.get("detail", ""))
        lines.append("    entries.Add(New DiagnosticTemplate(" + ", ".join(map(quote, values)) + "));")
    lines += ["    Return entries;", "}", "", "Safe Function string ChineseUi(string key)", "{"]
    ui = {key: value["text"] for key, value in chinese.items() if "text" in value}
    for key, value in ui.items():
        lines.append(f"    If (key == {quote(key)}) Return {quote(value)};")
    lines += ['    Return "";', "}", ""]
    diag = (ROOT / "apps/kinal/src/kn_diag.c").read_text(encoding="utf-8")
    literal = r'"(?:[^"\\]|\\.)*"'
    full = re.search(r'g_help_full_en\[\]\s*=\s*(.*?);', diag, re.S)
    assert full
    full_help = "".join(json.loads(part) for part in re.findall(literal, full[1]))
    ui_source = re.search(r'g_ui_templates\[\]\s*=\s*\{(.*?)\n\};', diag, re.S)
    assert ui_source
    lines += ["Safe Function list EnglishUi()", "{", "    list entries = list.Create();", "    LocaleEntry entry = null;"]
    for key, value in re.findall(r'\{\s*(' + literal + r'),\s*(' + literal + r'|g_help_full_en)\s*\}', ui_source[1]):
        text = full_help if value == 'g_help_full_en' else json.loads(value)
        lines += [f"    entry = New LocaleEntry({key});", f"    entry.Text = {quote(text)};", "    entries.Add(entry);"]
    lines += ["    Return entries;", "}", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if DESTINATION.read_text(encoding="utf-8") != expected:
            raise SystemExit("selfhost diagnostic catalog is stale; run infra/scripts/sync_selfhost_diagnostic_catalog.py")
    else:
        DESTINATION.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
